application: timesync-1061
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /pebble/.*resources/
  static_dir: templates/pebble/resources/

- url: /pebble/.*
  script: pebble.app

- url: .*/resources/
  static_dir: templates/resources/

- url: /privacy-policy/
  static_files: templates/privacy.html
  upload: templates/privacy.html

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /beta/upload/.*
  script: main.app
  login: admin
  auth_fail_action: redirect
  secure: always
  
- url: /admin/.*
  script: main.app
  login: admin
  auth_fail_action: redirect
  secure: always
  
- url: /stylesheets
  static_dir: templates/resources/css

- url: /delete/.*
  script: main.app
  secure: always
  
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: ssl
  version: latest