application: timesync-1061
version: 1
runtime: python27
api_version: 1
threadsafe: yes

includes:
- config/statics.yaml
- config/beta.yaml

handlers:

- url: /admin/.*
  script: apps.admin.app
  login: admin
  auth_fail_action: redirect
  secure: always

- url: /delete/.*
  script: apps.delete.app
  secure: always
  
- url: /cron/.*
  script: apps.cron.app
  secure: always
  login: admin
  
- url: /v\d*/callback/.*
  script: apps.callback.app
  secure: always
  
- url: /v\d*/analytics/.*
  script: apps.analytics.app
  secure: always
  
- url: /v\d*/.*
  script: apps.main.app
  secure: always
  
- url: /.*
  script: apps.404.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: ssl
  version: latest